{
 "title": "Railway_Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Critical Severity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS count\r\nFROM railway\r\nWHERE Severity = 'Critical';\r\n"
    }
   ]
  },
  {
   "title": "High Severity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS count\r\nFROM railway\r\nWHERE Severity = 'High';\r\n"
    }
   ]
  },
  {
   "title": "Medium Severity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS count\r\nFROM railway\r\nWHERE Severity = 'Medium';\r\n"
    }
   ]
  },
  {
   "title": "Low Severity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS count\r\nFROM railway\r\nWHERE Severity = 'Low';\r\n"
    }
   ]
  },
  {
   "title": "Count by Severity",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT Severity, COUNT(*) AS severity_count\r\nFROM railway\r\nWHERE Alert_Type != 'No Alert'\r\nGROUP BY Severity;\r\n"
    }
   ]
  },
  {
   "title": "Count by Alert type",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT Alert_Type, COUNT(*) AS alert_count\r\nFROM railway\r\nWHERE Alert_Type != 'No Alert'\r\nGROUP BY Alert_Type\r\nORDER BY alert_count DESC;\r\n"
    }
   ]
  },
  {
   "title": "Alerts by Station",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT Station, COUNT(*) AS total_alerts\r\nFROM railway\r\nWHERE \r\n    Alert_Type != 'No Alert' \r\nGROUP BY Station;\r\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 10, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT Alert_Type, Severity, COUNT(*) AS Alert_Count \r\nFROM railway \r\nGROUP BY Alert_Type, Severity \r\nORDER BY Severity DESC;\r\n"
    }
   ]
  }
 ]
}